- hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  pre_tasks:
    - name: Update Apt
      become: yes
      apt:
        update_cache: yes
        autoremove: yes
        upgrade: yes
      tags:
        - pkg
  tasks:
    # - include_tasks: tasks/ssh.yml
    # - include_tasks: tasks/git.yml
    # - include_tasks: tasks/pkgs.yml
    # - include_tasks: tasks/fish.yml
     - include_tasks: tasks/go.yml
    # - include_tasks: tasks/node.yml
    # - include_tasks: tasks/docker.yml
