# Setup repository
- name: Update apt
  become: yes
  apt:
    update_cache: yes
- name: Install pre-req packages
  become: yes
  apt:
    pkg:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
- name: create directory for docker keyring
  become: true
  shell: mkdir -p /etc/apt/keyrings
- name: add docker's official gpg key
  become: true
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
- name: setup the repository
  become: true
  shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

# Install engine
- name: Update packages
  become: yes
  apt:
    update_cache: yes
- name: Install engine
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
- name: Start docker service
  become: yes
  shell: service docker start
- name: Add user to docker group
  become: yes
  shell: usermod -aG docker $USER
- name: Activate changes to group
  shell: newgrp docker
- name: Verify installation
  shell: docker run hello-world
