# Setup fish shell
- name: Get fish ppa
  apt_repository: repo='ppa:fish-shell/release-3'
  tags:
    - fish
- name: Update repo cache
  become: yes
    apt:
      update_cache: yes
      autoremove: yes
      upgrade: yes
  tags:
    - fish
- name: Install fish
  apt: name=fish
  tags:
    - fish
- name: Change default shell to fish
  become: yes
  shell: chsh -s `which fish`
  tags:
    - fish
