# Install Go
- name: Pull update-golang script
  ansible.builtin.git:
    repo: "https://github.com/udhos/update-golang"
    dest: "~/.config/go-script"
  tags:
    - go
- name: Make it executable
  shell: chmod +x ~/.config/go-script/update-golang.sh
  tags:
    - go
- name: Run script to install go
  become: yes
  shell: ~/.config/go-script/update-golang.sh
  tags:
    - go
- name: Install golangci-lint
  become: yes
  shell: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b /usr/local/bin
