- name: Install packages
  become: yes
  apt:
    pkg:
      - fd-find
      - fzf
      - ripgrep
  tags:
    - pkg
- name: Update apt cache
  become: yes
  apt:
    update_cache: yes
  tags:
    - pkg
